### ISSUE TITLE
trying to switch to this vs the one its forked from

### ISSUE THREAD

**Issue by Eno423** [dzungpv/mitsubishi2MQTT#5] opened 2023-11-04 00:04 UTC
trying to compile using Arduino (for some reason platformio never flashes my d1 clones correctly)

after getting all the libs installed, I am not getting the following error

E:\electronics\MiniSplits\mitsubishi2MQTT-master\mitsubishi2MQTT-master\main\main.ino:712:26: error: 'HTTP_ASYNC_ANY' was not declared in this scope
  712 |     server.on("/upload", HTTP_ASYNC_ANY, handleUploadDone, handleUploadLoop);

**Comment by dzungpv** [comment] 2023-11-04 15:02
> trying to compile using Arduino (for some reason platformio never flashes my d1 clones correctly)
> 
> after getting all the libs installed, I am not getting the following error
> 
> E:\electronics\MiniSplits\mitsubishi2MQTT-master\mitsubishi2MQTT-master\main\main.ino:712:26: error: 'HTTP_ASYNC_ANY' was not declared in this scope 712 | server.on("/upload", HTTP_ASYNC_ANY, handleUploadDone, handleUploadLoop);

Use my fork instead origin libs: you can download all libs here and exact to Arduino/libs folder or using Arduino and install from zip file:
List of the require libs:
https://github.com/dzungpv/ESPAsyncWebServer.git (you may only need this)
https://github.com/dzungpv/HeatPump
https://github.com/dzungpv/async-mqtt-client
https://github.com/dzungpv/AsyncTCP.git
https://github.com/me-no-dev/ESPAsyncTCP
https://github.com/dzungpv/AsyncTCP.git

**Comment by Eno423** [comment] 2023-11-04 16:58
ok ill give that a shot. 

one other question, does using these to control the units completely break the remote control?

I managed to get a build working using the gysmo one, but seems my remote isnt controlling the unit properly.  

I even disconnected the wmos & turned off the breaker for 30 mins, but seems it turns on but now the remote wont contrl the fan or vane

**Comment by dzungpv** [comment] 2023-11-06 04:22
> ok ill give that a shot.
> 
> one other question, does using these to control the units completely break the remote control?
> 
> I managed to get a build working using the gysmo one, but seems my remote isnt controlling the unit properly.
> 
> I even disconnected the wmos & turned off the breaker for 30 mins, but seems it turns on but now the remote wont contrl the fan or vane

I don't understand what you mean. You using wall remote? You can post the model of the remote so I can check it, because I have only IR remote control.

**Comment by Eno423** [comment] 2023-11-06 18:10
sorry for not clarifying

seems my IR remote no longer can control the vane or the speed of the fan when on Heat. If I switch to Cool, those functions work fine.

I have a msz-gl09na . Im pretty sure this worked prior to connecting the wemos, but doesnt when it is connected or when it is removed. 
I aslo had a issue w/ my unit at one point seemingly not working unless I pressed the Emergency swtich ...then it beeped/flashed the 12 times which looking up the code, something about the non volitile flash of the controller board being non readable?

I have another 1 of these units in another room, when I get time today Ill run over & check that unit in heat mode allows me to to control the fan speed & vane

**Comment by dzungpv** [comment] 2023-11-07 01:21
> sorry for not clarifying
> 
> seems my IR remote no longer can control the vane or the speed of the fan when on Heat. If I switch to Cool, those functions work fine.
> 
> I have a msz-gl09na . Im pretty sure this worked prior to connecting the wemos, but doesnt when it is connected or when it is removed. I aslo had a issue w/ my unit at one point seemingly not working unless I pressed the Emergency swtich ...then it beeped/flashed the 12 times which looking up the code, something about the non volitile flash of the controller board being non readable?
> 
> I have another 1 of these units in another room, when I get time today Ill run over & check that unit in heat mode allows me to to control the fan speed & vane

I am not sure, but may be it is by design by the heatpump, If it is the eeprom problem, it will not working with all mode. I will close the issue, You can open thread in discussion about underrate code problem.

**Closed by dzungpv** 2023-11-07 01:21 UTC
